### ISSUE TITLE
06-25-2023 make: *** [Makefile:681: all] Error 2

### ISSUE THREAD

**Issue by chrisvictor** [InterLinked1/phreakscript#19] opened 2023-06-25 20:05 UTC
**## Platform RPi3b+  ##**
root@TEST--ASL30-K6CV:/# uname -a
Linux TEST--ASL30-K6CV 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
root@TEST--ASL30-K6CV:/# phreaknet info
WARNING: PhreakScript is out of date (most recent stable version is 0.3.4 (2023-06-18)) - run 'phreaknet update' to update
Hostname: TEST--ASL30-K6CV
Debian GNU/Linux 11 (bullseye)
Linux TEST--ASL30-K6CV 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Package Manager: apt-get
PhreakScript 0.3.3 (2023-05-25)

**## Install log attached ##**
[install log 06-25-2023.txt](https://github.com/InterLinked1/phreakscript/files/11860699/install.log.06-25-2023.txt)

**##Problem ##**
make[3]: Entering directory '/usr/src/dahdi-tools-3.2.0/xpp'
  CC       astribank_tool-astribank_tool.o
  CC       libastribank_la-astribank.lo
  CC       libastribank_la-mpptalk.lo
  CC       libastribank_la-astribank_license.lo
  CCLD     libastribank.la
  CCLD     astribank_tool
  CC       astribank_hexload-astribank_hexload.o
  CC       astribank_hexload-pic_loader.o
  CC       hexfile.lo
  CCLD     libhexfile.la
  CC       libecholoader_la-parse_span_specs.lo
  CC       libecholoader_la-echo_loader.lo
  CCLD     libecholoader.la
  CCLD     astribank_hexload
/usr/bin/ld: ./.libs/libecholoader.a(libecholoader_la-echo_loader.o): in function `init_octasic':
echo_loader.c:(.text+0x1700): undefined reference to `get_ver'
/usr/bin/ld: ./.libs/libecholoader.a(libecholoader_la-echo_loader.o): in function `echo_ver':
echo_loader.c:(.text+0x2290): undefined reference to `get_ver'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:739: astribank_hexload] Error 1
make[3]: Leaving directory '/usr/src/dahdi-tools-3.2.0/xpp'
make[2]: *** [Makefile:1061: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/dahdi-tools-3.2.0/xpp'
make[1]: *** [Makefile:1138: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/dahdi-tools-3.2.0'
make: *** [Makefile:681: all] Error 2
**DAHDI Tools compilation failed, aborting install**

**Comment by InterLinked1** [comment] 2023-06-25 23:51
Is there any difference from #16 here? Looks similar/the same to me...

**Comment by InterLinked1** [comment] 2023-08-01 18:20
Closing as duplicate of #16

**Closed by InterLinked1** 2023-08-01 18:20 UTC
Labels: bug
